[package]
name = "generic-kernel"
version.workspace = true
edition.workspace = true

[dependencies]
bootloader_api = "=0.11.10"
x86_64 = "=0.15.2"
spin = "=0.10.1"
kernel-core = { path = "../crates/kernel-core" }
noto-sans-mono-bitmap = { version = "=0.3.2", default-features = false, features = ["regular", "bold", "size_16", "size_20", "size_24", "unicode-basic-latin"] }

[features]
smoke = []

[[bin]]
name = "generic-kernel"
path = "src/main.rs"
test = false
bench = false
